### ISSUE TITLE
Two Punk Pixel Tips / Suggestions to Make Code Easier to Read 

### ISSUE THREAD

**Issue by geraldb** [Gardettos/ATSPunks#1]
Hello,

 From the commentary on your [CryptoPunksDev post that highlight your pixel punk scripts](https://old.reddit.com/r/CryptoPunksDev/comments/q2qu9g/punk_spotlight_gardettoss_create_your_own_punk/) that might interest you:

Tip one - Place attributes in a 24x24 canvas (images) - that makes composition easier - change

``` ruby
bigshades = Image.parse( <<TXT, colors: ['000000', 'F7F760'] ) #black and yellow color
. @ @ @ @ @ . @ @ @ @ @
. @ x x x @ @ @ x x x @
@ @ x x x @ . @ x x x @
. @ x x x @ . @ x x x @
. . @ @ @ . . . @ @ @ .
TXT
bigshades.save( "./MyPunks/Attributes/bigshades.png" )
```

to 

``` ruby
bigshades = Image.parse( <<TXT, colors: ['000000', 'F7F760'] ) #black and yellow color
. @ @ @ @ @ . @ @ @ @ @
. @ x x x @ @ @ x x x @
@ @ x x x @ . @ x x x @
. @ x x x @ . @ x x x @
. . @ @ @ . . . @ @ @ .
TXT
img = Image.new( 24, 24 )
img.compose!( bigshades, 6, 10 )  # place in 24x24 canvas with x/y offset 
img.save( "./MyPunks/Attributes/bigshades.png" )
```

Tip two -  When composing a punk start with an empty canvas (with your own background color)

``` ruby
punk = Image.new( 24, 24 )
human_light    = Punks::Sheet.find_by( name: 'Male 3' )
human_light = human_light.change_colors( { 0x000000 => 0x6A88A1 } )
punk.compose!( human_light )
```

change to 

``` ruby
punk = Image.new( 24, 24, '6A88A1' )
human_light = Punks::Sheet.find_by( name: 'Male 3' )
punk.compose!( human_light )
```

Cheers. Prost. Thanks for sharing your pixel punk scripts.

PS: For a complete pixel punk from scratch how-to inspired by your scripts, see [The Making of Adam (24x24 Pixel Punk) from Scratch / Zero Using Pixel Art Designs in the ASCII Text Format](https://github.com/cryptopunksnotdead/pixelart-howto/tree/master/adam):

**Comment by Gardettos** [comment]
Thank you sir! I recreated everything recently with some much cleaner code. I thoroughly enjoyed following your guides and have loved learning more about how crypto punks were made. I'm a C# dev by trade but your guides pushed me to learn a new language! I got married recently and the images you see in this repo were gifts to my nerdy groomsmen. Thank you again!

**Comment by geraldb** [comment]
Thanks for the update. Welcome to the wonders of ruby (scripting).  Wow - that was a great gift and idea. All the best.
